### ISSUE TITLE
Code blocks & R crashing 

### ISSUE THREAD

**Issue by xylimeng** [nasyring/GSOC-BayesBD#1]
In order to debug the R GUI crash issue, will it help if break the code into blocks and test them separately? Also, there are a lot of Rcpp's in the draft code, indicating pretty intense calls of C++ from R, does it seem to be a reason for the crash?

**Comment by nasyring** [comment]
Hi Dr Li,

I did some more testing of the code.  Mainly I tried to run after
commenting out certain sections.  This didn't keep the code from crashing,
but in some cases, it was able to run many more iterations before crashing
R.  So, I'm not sure yet of the problem, but it's possible that the code is
too computationally intense.

You had mentioned that the code looked like it might be intense to run.  Do
you have any thoughts on how I have structured the code using Rcpp?  Do you
know of a better way of using Rcpp? For example, I have written cpp
functions for the major parts of the sampling algorithm. Another approach
might be to use the inline package along with Rcpp to write inline c++
functions. I am not sure if this would run better.

I am in Europe now for the next week.  But,  I think that once I get the
code in good working order,  it should be straight forward to extend to the
continuous case.

Thanks,
Nick

**Comment by xylimeng** [comment]
Thanks for the update, Nick!

You may try to update the code sequentially while ensuring that you can "see" what's going on in the code. Focus on the binary case for now, and one possible strategy of coding structure is: 
1. Start an R session, generate observations. 
2. Start the main loop for MCMC (still in R). 
3. update parameter1 (call the function _update1_); update parameter2 (call the function _update2_); etc. 
4. collect all the posterior samples. 

All _update1_, _update2_, ... functions are written in C++ ; they are executable in c++, but you just export them to R in the end (either using Rcpp or write inline c++ functions, and I think the differences are not essential). 

By staying with an R interface, you fully have the control of what's going on (the memory usage, numerical results, say), and can obtain concrete results immediately. By using the c++ functions to update parameters in each MCMC run, you improve the speed. I think this strategy is practical but let me know if there's any confusion or so. 

The computational burden is not intensive and doesn't seem to be the reason of crashing R, since the original R function works well. It may be due to the intensive jumps between R and c++; we may want to do the coding as much as possible in c++ and then export to R just very few times (just one time ideally, which is the main function _BayesBDbinary_). BTW, When coding in c++, the Armadillo library is very handy.

**Comment by xylimeng** [comment]
Another suggestion for debugging: print out verbal messages at each MCMC run to track what's going on. For example, "1st run starts ...", "gamma = ...", "100th run starts ...", "memory used ....", etc.

**Comment by nasyring** [comment]
Hi Dr. Meng,

There is now an updated version of the Rcpp codes.  I took your advice and called the c++ update functions from an R loop.  This helped me to find the mistakes in the c++ updating functions and fix them.  Thanks for your good advice!  The example at the end of the code now works, using the c++ functions within the R loop.  The next step is to loop within c++.  there is code for this also, but has not yet been tested.

Thanks,
Nick

**Comment by xylimeng** [comment]
Hi Nick, 

I were out of town for a few days and just got back. 
Nice work! The progress is great and so glad to see this problem solved. I’ll close this “issue” in gitbhub and let’s proceed to next step. 

Best,
Meng
